### ISSUE TITLE
Help with the rmd, please...

### ISSUE THREAD

**Issue by vravigne** [oumaimamoubset/Phytovirus#4]
I attempted to produce all figures on plant distributions in a rmd file called Visualizing_plant_data.rmd, which sources the Distrib_cover_fred.R script. 

But it does not run. I suspect this is because of the very first instructions :
```{r plants, message=FALSE}
getwd() %>% 
  paste(.,"scripts/Distrib_cover_fred.R", sep="") %>% 
  source()
plant_data %>% summary()
```
An idea ?

**Comment by frederic-mahe** [comment]
Maybe an issue with the starting point when calling the Rmd file (`scripts` folder vs. root of the project)?
```R
getwd() %>% 
  paste(.,"../scripts/Distrib_cover_fred.R", sep="") %>% 
  source()
plant_data %>% summary()
```

**Comment by vravigne** [comment]
I think I found it. At least the Distrib_cover_fred.R script runs when sourced.
I have defined the knit directory as the project directory and replaced the getwd() instruction by
source("./scripts/Distrib_cover_fred.R")

**Comment by vravigne** [comment]
thx!
